"""
This module processes and summarizes text by interacting with the Groq
API. It splits a transcript into chunks, sends the chunks for
summarization, and outputs a refined summary of the entire text.

Functions:
- split_transcript: Splits a transcript into a specified number of
    chunks based on approximate length, ensuring the split occurs at
    sentence boundaries.
- _send_request: Sends a request to the Groq API to summarize or refine
    a chunk of text using a specified instruction.
- refine_summary: Combines and refines chunk summaries to produce a
    final summary.
- main: Entry point for executing the summarization process.

Usage:
The module can be used by importing it and calling the split_transcript
and refine_summary functions.
"""

# Import the built-in libraries.
import os

# Import the third-party libraries.
from dotenv import load_dotenv
from groq import Groq


# Initialize the Groq client with the API key from environment variables
load_dotenv()
client = Groq(api_key=os.environ.get("GROQ_API_KEY"))


def split_transcript(transcript: str, num_chunks: int) -> list:
    """Splits a transcript into a specified number of chunks.

    Splits a transcript into a specified number of chunks, ensuring
    that chunks are divided at the nearest sentence boundary (period).

    Args:
        transcript (str): The complete transcript.
        num_chunks (int): The number of chunks.

    Returns:
        list: A list of transcript chunks.
    """
    # Calculate the approximate size of each chunk.
    transcript_len = len(transcript)
    chunk_size = round(transcript_len / (num_chunks - 1))
    # Initialize an empty list to store the chunks and set the starting
    # index.
    chunks = []
    start = 0
    # Iterate over chunks
    for _ in range(num_chunks):
        end = start + chunk_size
        # Adjust the end index to find the nearest period before the
        # chunk boundary.
        if end < transcript_len:
            dot_index = transcript.rfind('.', start, end)
            if dot_index != -1:
                # Include the period in the chunk
                end = dot_index + 1
        # Append the current chunk to the list and update the starting
        # index.
        chunks.append(transcript[start:end].strip())
        start = end
    # Handle any remaining text that has not been included in the chunks
    if start < transcript_len:
        chunks.append(transcript[start:].strip())
    return chunks


def _send_request(instruction: str, chunk: str):
    """Sends a request to the Groq API to process a chunk of text.

    Sends a request to the Groq API to process a chunk of text based on
    the provided instruction.

    Args:
        instruction (str): The instruction for the Groq API.
        chunk (str): The chunk of text to be processed.

    Returns:
        str: The response content generated by the Groq API.
    """
    # Send a request to the Groq API with the provided instruction and
    # text chunk.
    response = client.chat.completions.create(
        messages=[
            {
                "role": "user",
                "content": f"{instruction}\n\nThe text:\n\n{chunk}",
            }
        ],
        model="llama3-groq-70b-8192-tool-use-preview",
        temperature=0,
        max_tokens=8192
    )
    # Return the response content.
    return response


def refine_summary(instruction: str, chunks: list) -> tuple:
    """Refines summaries of chunks to produce a final summary.

    Combines and refines summaries of chunks to produce a final summary
    by incrementally summarizing combined chunks.

    Args:
        instruction (str): The instruction for the Groq API.
        chunks (list): A list of transcript chunks.

    Returns:
        tuple: A tuple containing the final refined summary and the
            number of tokens used.
    """
    # Start with an empty summary
    current_summary = ""
    response = None
    # Incrementally refine the summary by combining each chunk
    for num, chunk in enumerate(chunks):
        # Combine the current summary with the next chunk
        if current_summary:
            combined_text = f"{current_summary}\n\n{chunk}"
        else:
            combined_text = chunk
        # Send the combined text for summarization
        response = _send_request(instruction, combined_text)
        current_summary = response.choices[0].message.content
        # print(
        #     f"Int. Summary after chunk {num + 1}:\n{current_summary}\n"
        # )
        # print(response.usage.completion_tokens)
    return current_summary, response.usage.completion_tokens


def main() -> None:
    """Entry point for executing the summarization process."""
    # Instruction for Groq.
    instruction = (
        "I give a chunk of a full text. Please summarize this. "
        "You should divide the chunk into several logical parts. "
        "The division should reflect a logical separation based on "
        "topics, themes, or any natural breakpoints in the text. "
        "Label each part with a brief heading that describes the focus or "
        "content of that section. Summarize every part.\n\n"
        "Please provide the output in the following format:\n\n"
        "Part 1: [Descriptive Heading]\n"
        "[The text from the first section]\n\n"
        "Part 2: [Descriptive Heading]\n"
        "[The text from the second section]\n"
    )
    # Path to the transcript file.
    transcript_path = "../data/cleaned_whisper_transcript_max_context_64.txt"
    with open(transcript_path, "r") as file:
        transcript = file.read()
    # Divide the transcript into 4 chunks using the split_transcript
    # function.
    chunks = split_transcript(transcript, 4)
    # Generate the refined summary using the refine_summary function.
    final_summary, token_num = refine_summary(instruction, chunks)
    # Output the final summary
    print("Final Summary:\n", final_summary)
    print("Number of tokens:\n", token_num)


if __name__ == "__main__":
    main()
